/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WhatsNewKitFeature } from "./components/whats-new-kit/whats-new-kit";
export namespace Components {
    interface TestComponent {
    }
    interface WhatsNewKit {
        "buttons": {
        more?: {
            title: string,
            color?: string,
            handler?: () => string;
        };
        continue: {
            title: string,
            color?: string,
            handler?: () => string;
        };
    };
        "features": WhatsNewKitFeature[];
        "title": string;
    }
}
declare global {
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLWhatsNewKitElement extends Components.WhatsNewKit, HTMLStencilElement {
    }
    var HTMLWhatsNewKitElement: {
        prototype: HTMLWhatsNewKitElement;
        new (): HTMLWhatsNewKitElement;
    };
    interface HTMLElementTagNameMap {
        "test-component": HTMLTestComponentElement;
        "whats-new-kit": HTMLWhatsNewKitElement;
    }
}
declare namespace LocalJSX {
    interface TestComponent {
    }
    interface WhatsNewKit {
        "buttons"?: {
        more?: {
            title: string,
            color?: string,
            handler?: () => string;
        };
        continue: {
            title: string,
            color?: string,
            handler?: () => string;
        };
    };
        "features"?: WhatsNewKitFeature[];
        "title"?: string;
    }
    interface IntrinsicElements {
        "test-component": TestComponent;
        "whats-new-kit": WhatsNewKit;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
            "whats-new-kit": LocalJSX.WhatsNewKit & JSXBase.HTMLAttributes<HTMLWhatsNewKitElement>;
        }
    }
}
